#### 安心学：以Python为主,C++ or 数据结构 可以答疑问或者课后再问。

#### 本学期计划：
1. 跟着上课学习的进度复习和预习python基础知识，最后会组织总复习。
2. 拓展python库：numpy,pandas (另一位辅导员会教seaborn和matplotib)
3. 剩下时间答疑。
4. 代码debug尽量在我和另一位辅导员上课的当天发群里或者私发给我们，尽力帮助。
5. questions?

#### Python 学习方法
1. 核心是practice
2. 基础语法和concepts掌握扎实
  btw，平时学习不要太纠结考试那种莫名其妙的选择题概念理解，对理解编程没有太多帮助。
3. 善用网络资源，包括但不限于使用Bing new chat 这里推荐：[Learn Python 2 | Codecademy](https://www.codecademy.com/learn/learn-python) 和 [Python3 教程 | 菜鸟教程 (runoob.com)](https://www.runoob.com/python3/python3-tutorial.html)
4. 请务必在初学独立完成代码

## Jupyter Notebook
这里强烈推荐一下Jupyter Notebook的一个插件：**nbextensions**
安装：pip install jupyter_contrib_nbextensions
[Package Manual](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html)
非常实用的功能：
* Table of Contents
* CodeFolding
* Highlighting
* Variable Inspector

安装库可以使用清华源 -i https://pypi.tuna.tsinghua.edu.cn/simple： 语法： pip install ... -i https://pypi.tuna.tsinghua.edu.cn/simple


#### review： 分支结构，循环结构

In [10]:
today = 4
if today == 1:
    print("周一")
elif today == 2:
    print("周二")
elif today == 3:
    print("周三")
else:
    print("周一周二周三之外的一天")

周一周二周三之外的一天


In [11]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [12]:
sum = 0
i = 0
while(i < 10):
    sum += i
    i += 1
print(sum)

45


In [13]:
count = 0
guess_num = 30
while guess_num != 20 and count <= 10:
    guess_num -= 1
    count += 1
    print(guess_num)

29
28
27
26
25
24
23
22
21
20


In [14]:
count = 0
guess_num = 10
while guess_num != 20:
    guess_num += 1
    count += 1
    if count > 10:
        break
    print(guess_num)

11
12
13
14
15
16
17
18
19
20


In [ ]:
cn_list = ['Apple', 'Facebook', 'Alibaba', 'Bilibili', 'Tesla', 'Tencent']
print(cn_list[-1])
print(cn_list[:3])
print(cn_list[2:4]) # 2<=index<4
print(cn_list[-3:])

Tencent
['Apple', 'Facebook', 'Alibaba']
['Alibaba', 'Bilibili']
['Bilibili', 'Tesla', 'Tencent']


#### break:弹出
#### continue:跳过一次循环继续

## Basics of Python
### Lists,Dictionaries,Tuple,Set

In [16]:
cn_list.append('Amazon')
cn_list

['Apple', 'Facebook', 'Alibaba', 'Bilibili', 'Tesla', 'Tencent', 'Amazon']

In [17]:
cn_list = cn_list + ['Luckin', 'Starbucks']
cn_list

['Apple',
 'Facebook',
 'Alibaba',
 'Bilibili',
 'Tesla',
 'Tencent',
 'Amazon',
 'Luckin',
 'Starbucks']

In [18]:
for i in range(9):
    print(i)
    print(cn_list[i])

0
Apple
1
Facebook
2
Alibaba
3
Bilibili
4
Tesla
5
Tencent
6
Amazon
7
Luckin
8
Starbucks


In [21]:
for i in range(len(cn_list)):
    print(i)
    if cn_list[i] in ['Luckin', 'Starbucks']:
        cn_list.remove(cn_list[i])

0
1
2
3
4
5
6
7
8


In [59]:
cn_list = ['Apple', 'Facebook', 'Alibaba', 'Bilibili', 'Tesla', 'Tencent']
cn_list.insert(4, 'KFC')
print(cn_list)

['Apple', 'Facebook', 'Alibaba', 'Bilibili', 'KFC', 'Tesla', 'Tencent']


总结一下list:
1.抽屉,每一格都是一个存储单元，每一格都可以单独获取。
2.index索引可以正着也可以反着
3.append or +[]
4.remove
5.insert

#### 给数据贴上标签 Dict
优势：Dictionary 无先后顺序、位置概念，索引速度并不会因为数据量变大而变慢

In [23]:
files = {"ID": 111, "passport": "my passport", "books": [1,2,3]}
print(files)
print(files["books"])

{'ID': 111, 'passport': 'my passport', 'books': [1, 2, 3]}
[1, 2, 3]


In [24]:
files["ID"] = 222
print(files)
files["ID"] = [2,3,4]
print(files)

{'ID': 222, 'passport': 'my passport', 'books': [1, 2, 3]}
{'ID': [2, 3, 4], 'passport': 'my passport', 'books': [1, 2, 3]}


In [25]:
files = {"ID": 111, "passport": "my passport", "books": [1,2,3]}

# 按key拿取，并在拿取失败的时候给一个设定好的默认值
print('files["ID"]:', files["ID"])

# 将另一个字典补充到当前字典
files.update({"files": ["1", "2"]})
print('update:', files)

# pop 调一个item，和列表的 pop 类似
popped = files.pop("ID")
print('popped:', popped)
print("remain:", files)

files["ID"]: 111
update: {'ID': 111, 'passport': 'my passport', 'books': [1, 2, 3], 'files': ['1', '2']}
popped: 111
remain: {'passport': 'my passport', 'books': [1, 2, 3], 'files': ['1', '2']}


In [26]:
files = {"ID": 111, "passport": "my passport", "books": [1,2,3]}
for key in files.keys():
    print("key:", key)

for value in files.values():
    print("value:", value)

for key, value in files.items():
    print("key:", key, ", value:", value)


key: ID
key: passport
key: books
value: 111
value: my passport
value: [1, 2, 3]
key: ID , value: 111
key: passport , value: my passport
key: books , value: [1, 2, 3]


#### tuple
特性：里面的元素不可变

In [27]:
files = ("file1", "file2", "file3")
print(files[1])

file2


In [28]:
files[1] = "file4"   # 这里会报错

TypeError: 'tuple' object does not support item assignment

#### set:集合
避免重复元素，无序性

In [29]:
my_files = set(["file1", "file2", "file3"])
print(my_files)
my_files.add("file3")
print(my_files)
my_files.add("file4")
print(my_files)
my_files.remove("file3")
print(my_files)

{'file1', 'file3', 'file2'}
{'file1', 'file3', 'file2'}
{'file4', 'file1', 'file3', 'file2'}
{'file4', 'file1', 'file2'}


In [30]:
print("my_files", my_files)
your_files = {"file1", "file3", "file5"}
print("your_files", your_files)
print("交集 ", your_files.intersection(my_files))
print("并集 ", your_files.union(my_files))
print("补集 ", your_files.difference(my_files))

my_files {'file4', 'file1', 'file2'}
your_files {'file1', 'file5', 'file3'}
交集  {'file1'}
并集  {'file1', 'file3', 'file4', 'file5', 'file2'}
补集  {'file5', 'file3'}


#### 总结：
[]：list
():tuple
{}:dict 或 set

#### numpy brief intro

是几乎所有Python其他库的核心，地位斐然。
广泛用于矩阵计算，人工智能，批处理，数据统计……
避免Python最让人诟病的速度慢的问题（见下）

In [31]:
# 使用numpy进行矩阵乘法
import numpy as np
import time

# 创建两个1000x1000的随机矩阵
a = np.random.rand(1000, 1000)
b = np.random.rand(1000, 1000)

# 记录开始时间
start = time.time()

# 使用numpy.dot函数进行矩阵乘法
c = np.dot(a, b)

# 记录结束时间
end = time.time()

# 打印运行时间
print(f"Using numpy: {end - start} seconds")

Using numpy: 0.011423587799072266 seconds


In [32]:
# 使用Python列表进行矩阵乘法
import random
import time

# 创建两个1000x1000的随机列表
a = [[random.random() for _ in range(1000)] for _ in range(1000)]
b = [[random.random() for _ in range(1000)] for _ in range(1000)]

# 记录开始时间
start = time.time()

# 矩阵乘法
c = [[0 for _ in range(1000)] for _ in range(1000)]
for i in range(1000):
    for j in range(1000):
        for k in range(1000):
            c[i][j] += a[i][k] * b[k][j]

# 记录结束时间
end = time.time()
# 打印运行时间
print(f"Using Python list:{end - start} seconds")

Using Python list:136.06967878341675 seconds


#### pip install numpy

In [33]:
import numpy as np


In [34]:
my_list = [1,2,3]
print(my_list[0])
my_array = np.array([1,2,3])
print(my_array[0])

1
1


In [35]:
my_list[0] = -1
my_array[0] = -1
print(my_list)
print(my_array)

[-1, 2, 3]
[-1  2  3]


In [36]:
cars = np.array([5, 10, 12, 6])
print("数据：", cars, "\n维度：", cars.ndim)

数据： [ 5 10 12  6] 
维度： 1


In [37]:
cars = np.array([
    [5, 10, 12, 6],
    [5.1, 8.2, 11, 6.3],
    [4.4, 9.1, 10, 6.6]
])

print("数据：\n", cars, "\n维度：", cars.ndim)

数据：
 [[ 5.  10.  12.   6. ]
 [ 5.1  8.2 11.   6.3]
 [ 4.4  9.1 10.   6.6]] 
维度： 2


In [38]:
cars = np.array([
    [
        [5, 10, 12, 6],
        [5.1, 8.2, 11, 6.3],
        [4.4, 9.1, 10, 6.6]
    ],
    [
        [6, 11, 13, 7],
        [6.1, 9.2, 12, 7.3],
        [5.4, 10.1, 11, 7.6]
    ],
])

print("总维度：", cars.ndim)
print("场地 1 数据：\n", cars[0], "\n场地 1 维度：", cars[0].ndim)
print("场地 2 数据：\n", cars[1], "\n场地 2 维度：", cars[1].ndim)

总维度： 3
场地 1 数据：
 [[ 5.  10.  12.   6. ]
 [ 5.1  8.2 11.   6.3]
 [ 4.4  9.1 10.   6.6]] 
场地 1 维度： 2
场地 2 数据：
 [[ 6.  11.  13.   7. ]
 [ 6.1  9.2 12.   7.3]
 [ 5.4 10.1 11.   7.6]] 
场地 2 维度： 2


In [39]:
cars1 = np.array([5, 10, 12, 6])
cars2 = np.array([5.2, 4.2])
cars = np.concatenate([cars1, cars2])  # 添加数据
print(cars)

[ 5.  10.  12.   6.   5.2  4.2]


In [40]:
test1 = np.array([5, 10, 12, 6])
test2 = np.array([5.1, 8.2, 11, 6.3])

# 首先需要把它们都变成二维，下面这两种方法都可以加维度
test1 = np.expand_dims(test1, 0)
test2 = test2[np.newaxis, :]

print("test1加维度后 ", test1)
print("test2加维度后 ", test2)

# 然后再在第一个维度上叠加
all_tests = np.concatenate([test1, test2])
print("括展后\n", all_tests)

test1加维度后  [[ 5 10 12  6]]
test2加维度后  [[ 5.1  8.2 11.   6.3]]
括展后
 [[ 5.  10.  12.   6. ]
 [ 5.1  8.2 11.   6.3]]


合并数据

In [41]:
print("第一维度叠加：\n", np.concatenate([all_tests, all_tests], axis=0))
print("第二维度叠加：\n", np.concatenate([all_tests, all_tests], axis=1))

第一维度叠加：
 [[ 5.  10.  12.   6. ]
 [ 5.1  8.2 11.   6.3]
 [ 5.  10.  12.   6. ]
 [ 5.1  8.2 11.   6.3]]
第二维度叠加：
 [[ 5.  10.  12.   6.   5.  10.  12.   6. ]
 [ 5.1  8.2 11.   6.3  5.1  8.2 11.   6.3]]


In [42]:
a = np.array([
    [1,2],
    [3,4]
])
b = np.array([
    [5,6],
    [7,8]
])
print("竖直合并\n", np.vstack([a, b]))
print("水平合并\n", np.hstack([a, b]))

竖直合并
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
水平合并
 [[1 2 5 6]
 [3 4 7 8]]


观察

In [43]:
cars = np.array([
    [5, 10, 12, 6],
    [5.1, 8.2, 11, 6.3],
    [4.4, 9.1, 10, 6.6]
])

count = 0
for i in range(len(cars)):
    for j in range(len(cars[i])):
        count += 1
print("总共多少测试数据：", count)

总共多少测试数据： 12


选取，切片

In [44]:
a = np.array([1, 2, 3])
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[[0,1]]:\n", a[[0,1]])
print("a[[1,1,0]]:\n", a[[1,1,0]])

a[0]: 1
a[1]: 2
a[[0,1]]:
 [1 2]
a[[1,1,0]]:
 [2 2 1]


In [45]:
b = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

# 选第 2 行所有数
print("b[1]:\n", b[1])

# 选第 2 行，第 1 列的数
print("b[1,0]:\n", b[1,0])

# 这个看着有点纠结，如果对应到数据，
# 第一个拿的是数据位是 [1,2]
# 第二个拿的是 [0,3]
print("b[[1,0],[2,3]]:\n",
      b[[1,0],
        [2,3]])

b[1]:
 [5 6 7 8]
b[1,0]:
 5
b[[1,0],[2,3]]:
 [7 4]


In [46]:
a = np.array([1, 2, 3])
print("a[0:2]：\n", a[0:2])
print("a[1:]：\n", a[1:])
print("a[-2:]：\n", a[-2:])
# 同list

a[0:2]：
 [1 2]
a[1:]：
 [2 3]
a[-2:]：
 [2 3]


In [47]:
b = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print("b[:2]:\n", b[:2])
print("b[:2, :3]:\n", b[:2, :3])
print("b[1:3, -2:]:\n", b[1:3, -2:])

b[:2]:
 [[1 2 3 4]
 [5 6 7 8]]
b[:2, :3]:
 [[1 2 3]
 [5 6 7]]
b[1:3, -2:]:
 [[ 7  8]
 [11 12]]


#### 条件筛选

In [48]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(a[a>7])

[ 8  9 10 11 12]


In [49]:
condition = a > 7
print(np.where(condition, -1, a))

[[ 1  2  3  4]
 [ 5  6  7 -1]
 [-1 -1 -1 -1]]


数据生成

In [50]:
import numpy as np
zeros = np.zeros([2, 3])
print("zeros:\n", zeros)

ones = np.ones([3, 2])
print("\nones:\n", ones)

data = np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.int64)

ones = np.ones(data.shape, dtype=data.dtype)
ones_like = np.ones_like(data)

print("ones:", ones.shape, ones.dtype)
print("ones_like:", ones_like.shape, ones_like.dtype)
print("ones_like value:\n", ones_like)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
ones: (2, 3) int64
ones_like: (2, 3) int64
ones_like value:
 [[1 1 1]
 [1 1 1]]


In [51]:
print("python range:", list(range(5)))
print("numpy arange:", np.arange(5))


python range: [0, 1, 2, 3, 4]
numpy arange: [0 1 2 3 4]


In [52]:
dim1, dim2 = 3, 2
print(np.random.rand(dim1, dim2)) # 你还能继续添加 dim3 或更多
print(np.random.random([dim1, dim2]))
print(np.random.randn(dim1, dim2))
print(np.random.randint(low=-3, high=6, size=10))

[[0.15657823 0.84940922]
 [0.5251306  0.16184726]
 [0.39912314 0.76850178]]
[[0.90838834 0.54804153]
 [0.89855918 0.03513744]
 [0.09212483 0.86121123]]
[[ 0.661513    0.00762249]
 [ 0.25182048  0.27886458]
 [-0.49993403  0.7409702 ]]
[-1  5 -3  4 -2  2  4 -3  0  4]


In [53]:
data = np.array([2,1,3,4,6])
print("选一个：", np.random.choice(data))
print("选多个：", np.random.choice(data, size=3))
print("不重复地选多个(不放回)：", np.random.choice(data, size=3, replace=False))
print("带权重地选择：", np.random.choice(data, size=10, p=[0,0,0,0.2,0.8]))


选一个： 1
选多个： [6 2 1]
不重复地选多个(不放回)： [3 6 2]
带权重地选择： [4 6 4 6 4 6 4 4 6 6]


In [54]:
data_copy = np.copy(data)
np.random.shuffle(data)
print("original数据：", data_copy)
print("shuffled:", data)

original数据： [2 1 3 4 6]
shuffled: [1 4 6 2 3]


In [55]:
# (均值，方差，size)
print("正态分布：", np.random.normal(1, 0.2, 10))

# (最低，最高，size)
print("均匀分布：", np.random.uniform(-1, 1, 10))

正态分布： [0.56275474 0.76774772 0.82816497 1.26646854 1.070128   1.14507802
 1.09563846 1.03356826 0.76268334 1.29069888]
均匀分布： [-0.13663734  0.52455351  0.35183975 -0.30318251 -0.63168156  0.80352552
  0.24844833 -0.8850982   0.71251335 -0.78781136]


In [56]:
# seed(1) 代表的就是 1 号随机序列
np.random.seed(1)
print(np.random.randint(2, 10, size=3))
print(np.random.randint(2, 10, size=3))

[7 5 6]
[2 9 3]
